import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Providers } from "@/lib/providers/providers";
import BottomAppBar from "./components/Shared/Header/BottomAppBar/BottomAppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Hunter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <div className="block md:hidden">
            <BottomAppBar />
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
